services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - coverage:/tests

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: backgammon

  client:
    build:
      context: ./client
    ports:
      - "8080:80"

  test:
    build:
      context: ./server
    command: ["pytest", "--disable-warnings", "-v", "--cov=./", "--cov-config=.coveragerc", "--cov-report=xml:/tests/server-coverage.xml"]
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    volumes:
      - coverage:/tests


  client-test:
    build:
      context: ./client
      target: build
    command: [ "npm", "run", "test" ]
    depends_on:
      - client

volumes:
  coverage: